/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'btu' at '8/19/15 5:48 PM' with Gradle 2.5
 *
 * @author btu, @date 8/19/15 5:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
